function generateTechnicalReport(results, txConfig)
% generateTechnicalReport Generates a comprehensive markdown report
% Now includes plots, DGA, Economic Analysis, and RUL.

if nargin < 2
    txConfig = defaultTransformerConfig(); % Fallback if not passed
end

fid = fopen('reports/TechnicalReport.md', 'w');
fprintf(fid, '# Fluxion - Comprehensive Digital Twin Technical Report\n\n');
fprintf(fid, 'This automated report is generated by the Fluxion Digital Twin engine. It contains physical, thermal, chemical, and economic evaluations of the transformer.\n\n');

fprintf(fid, '## 1. Transformer Nameplate & Base Parameters\n');
fprintf(fid, '- **Nominal Power:** %.2f MVA\n', txConfig.Sn / 1e6);
fprintf(fid, '- **Voltage (Primary / Secondary):** %.2f kV / %.2f kV\n', txConfig.V1n / 1000, txConfig.V2n / 1000);
fprintf(fid, '- **No-Load Loss (Core):** %.2f kW\n', txConfig.P0 / 1000);
fprintf(fid, '- **Load Loss (Copper):** %.2f kW\n', txConfig.Pcu / 1000);
fprintf(fid, '- **Equivalent Impedance (Zeq):** %.4f pu\n\n', sqrt(results.eqCircuit.pu.Req^2 + results.eqCircuit.pu.Xeq^2));

fprintf(fid, '## 2. Inrush & Transients Analysis\n');
fprintf(fid, 'A Monte Carlo simulation was executed with %d closing angle variations to determine the worst-case energization transients.\n', height(results.mc_results.table));
fprintf(fid, '- **Absolute Maximum Inrush Current:** %.2f A (%.2f pu)\n', max(results.mc_results.peak_currents), max(results.mc_results.peak_pu));
fprintf(fid, '![Inrush Waveform](../results/plot_01_Inrush_Waveform.png)\n\n');

fprintf(fid, '## 3. Thermal Analysis & Expected Life (RUL)\n');
fprintf(fid, 'The thermal dynamic model conforms to IEC 60076-7, estimating top-oil and winding hot-spot temperatures.\n');
fprintf(fid, '- **Top-Oil Steady-State:** %.1f °C\n', results.thermal_steady.top_oil);
fprintf(fid, '- **Hot-Spot Steady-State:** %.1f °C\n', results.thermal_steady.hot_spot);
if isfield(results, 'thermal_history')
    [V_st, ~] = tx.agingModel(results.thermal_history.hs(end), 1);
    exp_life = 30 / V_st;
    fprintf(fid, '- **Loss of Life Factor (V):** %.2f\n', V_st);
    fprintf(fid, '- **Expected Remaining Useful Life (RUL):** %.1f Years\n', exp_life);
end
fprintf(fid, '\n![Thermal Curve](../results/plot_06_Thermal_Curve.png)\n\n');

fprintf(fid, '## 4. Chemical Diagnosis: Dissolved Gas Analysis (DGA)\n');
fprintf(fid, 'Gas concentrations provided via config/sensors are mapped to the **Duval Triangle 1 (IEC 60599)**.\n');
fprintf(fid, '- **Methane (CH4):** %.1f ppm\n', txConfig.dga_CH4);
fprintf(fid, '- **Ethylene (C2H4):** %.1f ppm\n', txConfig.dga_C2H4);
fprintf(fid, '- **Acetylene (C2H2):** %.1f ppm\n', txConfig.dga_C2H2);
[zone, desc, pct] = tx.dgaModel.diagnose(txConfig.dga_CH4, txConfig.dga_C2H4, txConfig.dga_C2H2);
fprintf(fid, '- **Diagnosis:** %s (%s)\n\n', zone, desc);

fprintf(fid, '## 5. Economic & Cost Efficiency Analysis\n');
if isfield(txConfig, 'electricity_price')
    total_loss_kW = (txConfig.P0 + txConfig.Pcu)/1000; % Assuming nominal load
    daily_cost = total_loss_kW * 24 * txConfig.electricity_price;
    fprintf(fid, '- **Total Losses at Nominal Load:** %.1f kW\n', total_loss_kW);
    fprintf(fid, '- **Daily Wasted Energy Cost:** $%.2f\n', daily_cost);
    fprintf(fid, '- **Annual Operating Cost (Losses):** $%.0f\n', daily_cost * 365);
else
    fprintf(fid, 'Economic parameters not configured.\n');
end

fprintf(fid, '\n---\n*Report dynamically generated by Fluxion.*\n');
fclose(fid);
disp('Enhanced Technical report generated at reports/TechnicalReport.md');
end
